export const selectionRules = {
    cpu: { mode: "single" },
    motherboard: { mode: "single" },
    gpu: { mode: "single" },
    case: { mode: "single" },
    air_cooler: { mode: "single" },
    liquid_cooler: { mode: "single" },
    atx_power_supply: { mode: "single" },
    sfx_power_supply: { mode: "single" },
    ethernet_card: { mode: "single" },
    wifi_card: { mode: "single" },
    pcie_expansion_card: { mode: "single" },
    keyboard: { mode: "single" },
    mouse: { mode: "single" },
    operating_system: { mode: "single" },

    ram: { mode: "multiple", max: 4 },
    hdd: { mode: "multiple", max: 8 },
    ssd: { mode: "multiple", max: 8 },
    rgb_ligthing: { mode: "multiple", max: 4 },
    fan_controller: { mode: "multiple", max: 6 },
    monitor: { mode: "multiple", max: 3 },
    device_drivers: { mode: "multiple", max: 2 },
    utilities: { mode: "multiple", max: 6 },
};